
bash 01_file_creation_with_touch.sh
bash 02_file_creation_with_redirection.sh
bash 03_dir_creation_with_mkdir.sh
bash 04_empty_dir_reading_with_ls.sh
bash 05_non_empty_dir_reading_with_ls.sh
bash 06_file_reading_with_cat.sh
bash 07_file_overwrite_with_redirection.sh
bash 08_file_append_with_redirection.sh
bash 09_file_deletion_with_rm.sh
bash 10_empty_dir_deletion_with_rmdir.sh
bash 11_non_empty_dir_deletion_with_rm.sh
